USE [master]
GO
/****** Object:  Database [SW2_StoreDB]    Script Date: 18/04/2020 10:36:57 PM ******/
CREATE DATABASE [SW2_StoreDB] ON  PRIMARY 
( NAME = N'SW2_StoreDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SW2_StoreDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SW2_StoreDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SW2_StoreDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SW2_StoreDB] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SW2_StoreDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SW2_StoreDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SW2_StoreDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SW2_StoreDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SW2_StoreDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SW2_StoreDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SW2_StoreDB] SET RECOVERY FULL 
GO
ALTER DATABASE [SW2_StoreDB] SET  MULTI_USER 
GO
ALTER DATABASE [SW2_StoreDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SW2_StoreDB] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SW2_StoreDB', N'ON'
GO
USE [SW2_StoreDB]
GO
/****** Object:  Table [dbo].[UserInfo]    Script Date: 18/04/2020 10:36:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserInfo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FName] [nvarchar](255) NULL,
	[LName] [nvarchar](255) NULL,
	[Email] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[CreditId] [nvarchar](50) NULL,
	[PhoneNum] [nvarchar](50) NULL,
	[Address] [nvarchar](512) NULL,
	[IsLoggedIn] [bit] NOT NULL,
	[UserType] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_UserInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[UserInfo] ON 
GO
INSERT [dbo].[UserInfo] ([ID], [FName], [LName], [Email], [Password], [CreditId], [PhoneNum], [Address], [IsLoggedIn], [UserType]) VALUES (8, NULL, NULL, N'test', N'test', NULL, NULL, NULL, 1, N'admin')
GO
SET IDENTITY_INSERT [dbo].[UserInfo] OFF
GO
ALTER TABLE [dbo].[UserInfo] ADD  CONSTRAINT [DF_UserInfo_isLoggedIn]  DEFAULT ((0)) FOR [IsLoggedIn]
GO
ALTER TABLE [dbo].[UserInfo] ADD  CONSTRAINT [DF_UserInfo_UserType]  DEFAULT ('normal') FOR [UserType]
GO
USE [master]
GO
ALTER DATABASE [SW2_StoreDB] SET  READ_WRITE 
GO
